### ISSUE TITLE
Eliminación de un diagrama

### ISSUE THREAD

**Issue by SpunBeat** [SpunBeat/itbook-03062016#20]
Es necesario un botón para eliminar el diagrama o para guardarlo vacío

**Comment by IsaVargas** [comment]
Repetí este issue en el número 21...se puede borrar éste?

**Comment by IsaVargas** [comment]
Al eliminar un diagrama regresar a la pantalla de Seleccionar MAcroproceso, no mantener en macroproceso que se acaba de eliminar.
